ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'WORKSPACE_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'WORKSPACE_VIEWER';

UPDATE "User"
SET "role" = 'SUPER_ADMIN'::"Role"
WHERE "role"::text = 'ADMIN';

ALTER TABLE "User"
  ALTER COLUMN "role" SET DEFAULT 'WORKSPACE_ADMIN'::"Role";
